MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    NUM_GROUPS: 28
DATASETS:
  TRAIN: ("human_protein_train",)
  TEST: ("human_protein_test",)
DATALOADER:
  ASPECT_RATIO_GROUPING: false
SOLVER:
  BASE_LR: 0.02
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (512, 512, 512, 512, 512, 512)
OUTPUT_DIR: "output"
VERSION: 2
